stages:
  - deploy

publish:
  image: curlimages/curl:latest
  stage: deploy
  variables:
    ApiEndpoint: "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/composer"
    JobTokenHeader: "Job-Token: $CI_JOB_TOKEN"
  script:
    # Add package for tags, otherwise create package based on commit branch.
    - BuildTag=$( test -z "$CI_COMMIT_TAG" && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG" )
    - Response=$( curl --silent --write-out "\n%{http_code}" --header "$JobTokenHeader" --data "$BuildTag" "$ApiEndpoint" )
    - ResponseCode=$( echo "$Response" | tail -n 1 )
    - ResponseBody=$( echo "$Response" | head -n 1 )
    - |-
      if test "$ResponseCode" -eq "201";
      then
        echo "Composer package created: $ResponseBody";
      else
        echo "Composer package creation failed, error $ResponseCode: $ResponseBody" >&2;
        exit 1;
      fi
